version: '3.8'
networks:
    app_network:
services: 
    main:
        container_name: laravel_app
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./code:/var/www/html/
        ports:
            - 8000:8000
        networks:
            - app_network
    db:
        container_name: app_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'YzzYTr9yRkAZaq'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        networks:
            - app_network